//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioTargetSistemas.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesafioTargetSistemas.Exception.ResourceMessageException", typeof(ResourceMessageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The description exceeds the maximum allowed length..
        /// </summary>
        public static string DESCRIPTION_TOO_LONG {
            get {
                return ResourceManager.GetString("DESCRIPTION_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The due date cannot be in the past..
        /// </summary>
        public static string DUE_DATE_IN_THE_PAST {
            get {
                return ResourceManager.GetString("DUE_DATE_IN_THE_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The due date exceeds the maximum allowed period..
        /// </summary>
        public static string DUE_DATE_TOO_FAR {
            get {
                return ResourceManager.GetString("DUE_DATE_TOO_FAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The same product cannot appear more than once in a sale..
        /// </summary>
        public static string DUPLICATED_PRODUCTS_IN_SALE {
            get {
                return ResourceManager.GetString("DUPLICATED_PRODUCTS_IN_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insufficient stock for this outbound movement..
        /// </summary>
        public static string INSUFFICIENT_STOCK {
            get {
                return ResourceManager.GetString("INSUFFICIENT_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The start date cannot be after the end date..
        /// </summary>
        public static string INVALID_DATE_RANGE {
            get {
                return ResourceManager.GetString("INVALID_DATE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The movement type must be IN or OUT..
        /// </summary>
        public static string INVALID_MOVEMENT_TYPE {
            get {
                return ResourceManager.GetString("INVALID_MOVEMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The quantity must be greater than zero..
        /// </summary>
        public static string INVALID_QUANTITY {
            get {
                return ResourceManager.GetString("INVALID_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The request is invalid..
        /// </summary>
        public static string INVALID_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The seller id is invalid..
        /// </summary>
        public static string INVALID_SELLER_ID {
            get {
                return ResourceManager.GetString("INVALID_SELLER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The product code is required..
        /// </summary>
        public static string PRODUCT_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The product code exceeds the maximum allowed length..
        /// </summary>
        public static string PRODUCT_CODE_TOO_LONG {
            get {
                return ResourceManager.GetString("PRODUCT_CODE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product not found..
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The sale must have at least one item..
        /// </summary>
        public static string SALE_ITEMS_REQUIRED {
            get {
                return ResourceManager.GetString("SALE_ITEMS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seller not found..
        /// </summary>
        public static string SELLER_NOT_FOUND {
            get {
                return ResourceManager.GetString("SELLER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
